/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application.view;

/**
 *
 * @author Luism
 */
public class ProcessSummaryPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessSummaryPanel
     */
    public ProcessSummaryPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cpuLabel6 = new javax.swing.JLabel();
        cpuLabel7 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        pidLabel = new javax.swing.JLabel();
        cpuLabel = new javax.swing.JLabel();
        startTimeLabel = new javax.swing.JLabel();
        finishTimeLabel = new javax.swing.JLabel();
        cpuLabel5 = new javax.swing.JLabel();
        timeInSeconds = new javax.swing.JLabel();
        cpuLabel9 = new javax.swing.JLabel();

        cpuLabel6.setText("00:00");

        cpuLabel7.setText("Finish time: ");

        nameLabel.setText("Name");

        pidLabel.setText("100");

        cpuLabel.setText("Start time: ");

        startTimeLabel.setText("00:00");

        finishTimeLabel.setText("00:00");

        cpuLabel5.setText("Finish time: ");

        timeInSeconds.setText("0");

        cpuLabel9.setText("Seconds:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pidLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cpuLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cpuLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finishTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cpuLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeInSeconds, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(387, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cpuLabel9)
                        .addComponent(timeInSeconds))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cpuLabel5)
                        .addComponent(finishTimeLabel))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pidLabel)
                        .addComponent(nameLabel)
                        .addComponent(cpuLabel)
                        .addComponent(startTimeLabel)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel cpuLabel;
    public javax.swing.JLabel cpuLabel5;
    public javax.swing.JLabel cpuLabel6;
    public javax.swing.JLabel cpuLabel7;
    public javax.swing.JLabel cpuLabel9;
    public javax.swing.JLabel finishTimeLabel;
    public javax.swing.JLabel nameLabel;
    public javax.swing.JLabel pidLabel;
    public javax.swing.JLabel startTimeLabel;
    public javax.swing.JLabel timeInSeconds;
    // End of variables declaration//GEN-END:variables
}
